### ISSUE TITLE
After switching to version 1.7.1 getting below error

### ISSUE THREAD

**Issue by Dwapayan** [splunk/splunk-library-javalogging#109]
ERROR Unable to invoke factory method in class com.splunk.logging.HttpEventCollectorLog4jAppender for element SplunkHttp: java.lang.NoClassDefFoundError: org/apache/http/HttpEntity java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:136)

**Comment by loganknecht** [comment]
Hi @Dwapayan 

Thank you for reaching out regarding this issue! In order to facilitate us on this can you provide some additional information?

- Operating system and version
- Steps to reproduce
- Any related code snippets for this
- And any related log files

**Comment by Dwapayan** [comment]
1. Operating system version Windows 10 1809  (OS Build 17763.316)
2. added the following dependencies using graddle 
dependencies {
    compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.11.2'
    compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.11.2'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

3. Added reference jar file splunk-library-javalogging-1.7.1 as below does not work with graddle 
compile group: 'com.splunk.logging', name: 'splunk-library-javalogging', version: '1.7.1' 

Error:java: Illegal char <:> at index 81: C:\Users\Administrator\ideaProjects\logger-test\Could not find com.splunk.logging:splunk-library-javalogging:1.7.1.
Searched in the following locations:
  - https:\repo.maven.apache.org\maven2\com\splunk\logging\splunk-library-javalogging\1.7.1\splunk-library-javalogging-1.7.1.pom
  - https:\repo.maven.apache.org\maven2\com\splunk\logging\splunk-library-javalogging\1.7.1\splunk-library-javalogging-1.7.1.jar

4. this line in main is causing failure 
private static final Logger LOGGER = org.apache.logging.log4j.core.LoggerContext.getContext().getLogger("LoggerTest");

with XML 

<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="trace" name="LoggerTest" packages="">
    <Appenders>
        <SplunkHttp
            name="http"
            url="https://url"
            token="00000000-0000-0000-0000-000000000000"
            host=""
            batch_interval="0"
            disableCertificateValidation="true">
            <PatternLayout pattern="%m"/>
        </SplunkHttp>
    </Appenders>

    <Loggers>
        <Root level="INFO"/>
        <Logger name="LoggerTest" level="info">
            <AppenderRef ref="http"/>
        </Logger>
    </Loggers>
</Configuration>

**Comment by Dwapayan** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="trace" name="LoggerTest" packages="">
    <Appenders>
        <SplunkHttp
            name="http"
            url="https://url"
            token="00000000-0000-0000-0000-000000000000"
            host=""
            batch_interval="0"
            disableCertificateValidation="true">
            <PatternLayout pattern="%m"/>
        </SplunkHttp>
    </Appenders>

    <Loggers>
        <Root level="INFO"/>
        <Logger name="LoggerTest" level="info">
            <AppenderRef ref="http"/>
        </Logger>
    </Loggers>
</Configuration>

**Comment by Dwapayan** [comment]
"<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="trace" name="LoggerTest" packages="">
    <Appenders>
        <SplunkHttp
            name="http"
            url="https://url"
            token="00000000-0000-0000-0000-000000000000"
            host=""
            batch_interval="0"
            disableCertificateValidation="true">
            <PatternLayout pattern="%m"/>
        </SplunkHttp>
    </Appenders>
    <Loggers>
        <Root level="INFO"/>
        <Logger name="LoggerTest" level="info">
            <AppenderRef ref="http"/>
        </Logger>
    </Loggers>
</Configuration>"

**Comment by Dwapayan** [comment]
<Configuration status="trace" name="LoggerTest" packages="">
    <Appenders>
        <SplunkHttp
            name="http"
            url="https://url"
            token="00000000-0000-0000-0000-000000000000"
            host=""
            batch_interval="0"
            disableCertificateValidation="true">
            <PatternLayout pattern="%m"/>
        </SplunkHttp>
    </Appenders>
    <Loggers>
        <Root level="INFO"/>
        <Logger name="LoggerTest" level="info">
            <AppenderRef ref="http"/>
        </Logger>
    </Loggers>
</Configuration>

**Comment by Dwapayan** [comment]
![image](https://user-images.githubusercontent.com/4157781/53548130-c6cc1300-3b56-11e9-83ba-ea9e4752ccdf.png)

**Comment by Dwapayan** [comment]
ERROR Unable to invoke factory method in class com.splunk.logging.HttpEventCollectorLog4jAppender for element SplunkHttp: java.lang.NoClassDefFoundError: org/apache/http/HttpEntity java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:136)

**Comment by loganknecht** [comment]
Hey @Dwapayan I believe the solution is to change your `<AppenderRef ref="http" />` to `<AppenderRef ref="splunkhttp" />`.

Please let us know if this resolves the issue.

**Comment by Dwapayan** [comment]
Hi Admin,

I ma getting the same error with the suggested change 

![image](https://user-images.githubusercontent.com/4157781/53623036-d1071380-3c21-11e9-9b2d-6d42fa6bc0bf.png)

 ERROR Unable to invoke factory method in class com.splunk.logging.HttpEventCollectorLog4jAppender for element SplunkHttp: java.lang.NoClassDefFoundError: org/apache/http/HttpEntity java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:136)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:964)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:904)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:896)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:514)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:238)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:250)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:548)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:620)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:637)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:231)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:155)
	at org.apache.logging.log4j.core.LoggerContext.getContext(LoggerContext.java:171)
	at LoggerTest.<clinit>(LoggerTest.java:6)
Caused by: java.lang.NoClassDefFoundError: org/apache/http/HttpEntity
	at com.splunk.logging.HttpEventCollectorLog4jAppender.<init>(HttpEventCollectorLog4jAppender.java:82)
	at com.splunk.logging.HttpEventCollectorLog4jAppender.createAppender(HttpEventCollectorLog4jAppender.java:182)
	... 20 more
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpEntity
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 22 more

Thanks for all the help in advance.

**Comment by Dwapayan** [comment]
This issue is resolved we were able to solve it by pulling the library through maven.

**Comment by bhargav00200** [comment]
@Dwapayan  Pls paste here the working configuration, so that it helps to others.

**Comment by Priti0709** [comment]
Hi Dwapayan, 

Can you please share the solution for the above issue, as i am also facing the same issue:

2020-02-21 18:15:44,372 localhost-startStop-1 ERROR Unable to invoke factory method in class class com.splunk.logging.HttpEventCollectorLog4jAppender for element SplunkHttp. java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:132)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
        at org.apache.logging.log4j.core.LoggerContext.setConfigLocation(LoggerContext.java:603)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:157)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:74)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:227)
        at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:159)
        at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:131)
        at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:101)
        at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:188)
        at com.dotmarketing.loggers.Log4jUtil.initializeFromPath(Log4jUtil.java:146)
        
Caused by: java.lang.NoSuchFieldError: EMPTY_ARRAY
        at com.splunk.logging.HttpEventCollectorLog4jAppender.<init>(HttpEventCollectorLog4jAppender.java:78)
        at com.splunk.logging.HttpEventCollectorLog4jAppender.createAppender(HttpEventCollectorLog4jAppender.java:191)
        ... 36 more

**Comment by Priti0709** [comment]
I am using splunk logging master version : 1.8.0
was expecting all the issues would have been addressed in this version but m still facing a lot of issues:

Configuration:

<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
		
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{HH:mm:ss.SSS}  %-5level %logger{2} - %msg%n" />
        </Console>
		<SplunkHttp name="http-input"
              url="<our Server>"
              token="<my token>"
              host=""
              index="<my index>"
              source=""
              sourcetype=""
              messageFormat="text"
              middleware=""
              batch_size_bytes="0"
              batch_size_count="0"
              batch_interval="0"
              disableCertificateValidation="true">
            <PatternLayout pattern="%m"/>
        </SplunkHttp>
    </Appenders>
    <Loggers>
        <Root level="ERROR">
            <AppenderRef ref="Console" />
        </Root>
		
		<Logger name="LoggerTest" level="info">
			<AppenderRef ref="http-input"/>
		</Logger>
    </Loggers>
</Configuration>

**Comment by Priti0709** [comment]
> This issue is resolved we were able to solve it by pulling the library through maven.

Can you please share the solution for the same ?

**Comment by Priti0709** [comment]
> This issue is resolved we were able to solve it by pulling the library through maven.

Which Library ???

**Comment by KANNAN080701** [comment]
Hi
http-nio-8081-exec-3 ERROR Unable to invoke factory method in class com.splunk.logging.HttpEventCollectorLog4jAppender for element SplunkHttp: java.lang.IllegalStateException: No factory method found for class com.splunk.logging.HttpEventCollectorLog4jAppender java.lang.IllegalStateException: No factory method found for class com.splunk.logging.HttpEventCollectorLog4jAppender
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:234)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:134)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:579)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:651)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:668)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:243)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:648)
        at org.apache.logging.log4j.LogManager.getRootLogger(LogManager.java:682)
        at com.Employee.FetchADUsers.<init>(FetchADUsers.java:22)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:150)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1070)
        at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:788)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:128)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)

2022-12-06 12:24:00,456 http-nio-8081-exec-3 ERROR appenders Appenders has no parameter that matches element SplunkHttp
2022-12-06 12:24:00,476 http-nio-8081-exec-3 ERROR Unable to locate appender "splunk" for logger config "root"

Hi @Dwapayan @Priti0709 Im also facing the same issue, am using loh4j2-api-2.12.1.jar and splunk-libray-javalogging-1.11.7.jar. Can you please share the solution and right jar files. I cant find the jar fils for javalogging library?
